- .travis.yml
- build.gradle
> chore: another build.gradle update

- .circleci/config.yml
The working directory was set as `java-client`.
> chore: set semantically correct working directory

- .circleci/config.yml
- .codecov.yml
Adds Codecov to CircleCI config.
> chore: add codecov to circleci config

- README.md
- build.gradle
Changes `ARK` to `Ark` where appropriate.
> chore: adhere to naming convention

- build.gradle
Bypassing signing if building local packages from source
> chore: sign only when keyId present / gradle

- build.gradle
- src/test/java/org/arkecosystem/crypto/networks/DevnetTest.java
https://docs.gradle.org/4.8/release-notes.html#overwriting-gradle's-built-in-tasks
> chore: replace wrapper task with wrapper config

- src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
> fix: cast type to int

- CHANGELOG.md
- build.gradle
- src/main/java/org/arkecosystem/crypto/transactions/builder/AbstractTransaction.java
> fix: set network

- CHANGELOG.md
- build.gradle
- src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
Added export toHashMap - needed to convert the array of TransactionPayloads to Gson later on.
> refactor: changes to Transaction object class

- src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
> feat: support new vendorfield length

- CHANGELOG.md
- build.gradle
A summary of what changes this PR introduces and why they were made.
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
> release: 0.1.4

- CHANGELOG.md
- build.gradle
A summary of what changes this PR introduces and why they were made.
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
> release: 0.1.5

- build.gradle
- src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
- src/main/java/org/arkecosystem/crypto/utils/Message.java
A summary of what changes this PR introduces and why they were made.
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
> chore: downgrade bitcoinj-core to 0.14.7

- CHANGELOG.md
- build.gradle
A summary of what changes this PR introduces and why they were made.
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
> release: 0.1.6

- build.gradle
- src/main/java/org/arkecosystem/crypto/transactions/builder/AbstractBuilder.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/AbstractTransactionBuilder.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/DelegateRegistration.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/DelegateResignation.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/HtlcClaim.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/HtlcLock.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/HtlcRefund.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/Ipfs.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/MultiPayment.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistration.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/SecondSignatureRegistration.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/Transfer.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/Vote.java
What changes are being made? 
Rename `AbstractTransaction` to `AbstractBuilder`.
Why are these changes necessary? 
Making it more readable .
> style: rename AbstractTransaction to AbstractBuilder

- build.gradle
- src/main/java/org/arkecosystem/crypto/transactions/Transaction.java
- src/main/java/org/arkecosystem/crypto/utils/Message.java
With the bitcoinj update additional `SignatureDecodeException` needs to be handled.
> fix: handle SignatureDecodeException

- build.gradle
- src/main/java/org/arkecosystem/crypto/configuration/Fee.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/AbstractTransactionBuilder.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistration.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/SecondSignatureRegistration.java
What changes are being made? 
Upgraded spotless plugin to version 3.27.1
> chore: spotless plugin

- .github/workflows/test.yml
Add github actions matrix test for different JDK versions
> chore: add actions for different JDK versions

- build.gradle
What changes are being made? 
Added a task to build standalone jars.
Why are these changes necessary?
It gives you a possibility to build jars independently, even if they are not published to maven repository.
> feat: added a task to build standalone jars

- .github/workflows/publish-release.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Added support for releasing the package to github packages repository
- Update gradle file and cleaned old relics
> chore: added github actions release workflow

- .github/workflows/publish-release.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
* chore(deps): update dependency gradle to v6.2.0 (#107)
Co-authored-by: WhiteSource Renovate <renovatebot@gmail.com>
* chore: github actions publish release workflow
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: WhiteSource Renovate <renovatebot@gmail.com>
> release: 1.0.1

- build.gradle
- settings.gradle
> fix: gradle root project naming

- build.gradle
> chore: version bump in build.gradle

- src/main/java/org/arkecosystem/crypto/transactions/Serializer.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/AbstractTransactionBuilder.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/DelegateRegistrationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/DelegateResignationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcClaimBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcLockBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcRefundBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/IpfsBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/MultiPaymentBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistrationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/SecondSignatureRegistrationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/TransferBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/VoteBuilderTest.java
What changes are being made?
- Increase test coverage. Close Issue #118 
- Removed typeGroup method from builder class.
- Refactored serialization.
Why are these changes necessary? 
TypeGroup method was removed because the method was migrated to Abstract Transaction in previous PRs.
Serialization refactor: make it possible to serialize larger asset fields.
> test: increase test coverage

- .github/workflows/publish-release.yml
- build.gradle
- src/main/java/org/arkecosystem/crypto/transactions/Serializer.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/AbstractTransactionBuilder.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/DelegateRegistrationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/DelegateResignationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcClaimBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcLockBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/HtlcRefundBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/IpfsBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/MultiPaymentBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistrationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/SecondSignatureRegistrationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/TransferBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/VoteBuilderTest.java
- refactor of serialization process (dynamically allocation of  bytebuffer - transaction size)
- increase test coverage
- updated dependencies
> release: 1.2.1

- .github/workflows/publish-release-gpr.yml
- .github/workflows/publish-release-maven.yml
- build.gradle
> fix: github actions split workflows

- build.gradle
> release: 1.2.9

- renovate.json
> chore: update renovate to send PR to develop

- build.gradle
> Kristjank patch 1

- .github/workflows/release.yml
- .github/workflows/test.yml
- build.gradle
Adding a release workflow to GitHub Actions to publish the built artifacts to Maven Central.
> chore: refactor build script and automate release

- renovate.json
- src/test/java/org/arkecosystem/crypto/transactions/builder/VoteBuilderTest.java
Check unvote, unvote+vote, unvote+vote+secondsig
> test: core v3 transactions

- .github/workflows/test.yml
> chore: update java versions

- .github/workflows/test.yml
- src/main/java/org/arkecosystem/crypto/Schnorr.java
- src/main/java/org/arkecosystem/crypto/signature/ECDSASigner.java
- src/main/java/org/arkecosystem/crypto/signature/SchnorrSigner.java
- src/main/java/org/arkecosystem/crypto/signature/SchnorrVerifier.java
- src/main/java/org/arkecosystem/crypto/signature/Signer.java
- src/main/java/org/arkecosystem/crypto/signature/Verifier.java
- src/main/java/org/arkecosystem/crypto/transactions/Deserializer.java
- src/main/java/org/arkecosystem/crypto/transactions/Serializer.java
- src/main/java/org/arkecosystem/crypto/transactions/TransactionAsset.java
- src/main/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistrationBuilder.java
- src/main/java/org/arkecosystem/crypto/transactions/types/MultiSignatureRegistration.java
- src/main/java/org/arkecosystem/crypto/transactions/types/Transaction.java
- src/test/java/org/arkecosystem/crypto/SchnorrTest.java
- src/test/java/org/arkecosystem/crypto/signature/ECDSASignerTest.java
- src/test/java/org/arkecosystem/crypto/signature/ECDSAVerifierTest.java
- src/test/java/org/arkecosystem/crypto/signature/FixtureSignVerificationTest.java
- src/test/java/org/arkecosystem/crypto/signature/SchnorrSignerTest.java
- src/test/java/org/arkecosystem/crypto/signature/SchnorrVerifierTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/MultiSignatureRegistrationBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/builder/VoteBuilderTest.java
- src/test/java/org/arkecosystem/crypto/transactions/deserializers/DeserializerTest.java
> chore: auto format code

- src/main/java/org/arkecosystem/crypto/transactions/builder/VoteBuilder.java
> fix: use network to calculate recipient address when signing vote transaction

- build.gradle
> release: 2.0.0-beta-1

- build.gradle
> fix: maven repo url

- build.gradle
> fix: publishing to maven

- .github/workflows/release.yml
- build.gradle
> chore: sign artifacts for release

- .github/workflows/test.yml
> chore: java 17 support
